### ISSUE TITLE
执行sh bin/htmlc，提示报错信息

### ISSUE THREAD

**Issue by jxgxldl** [keevol/pandoc_md_book_starter#1]
报错如下
Traceback (most recent call last):
  File "/usr/bin/markdown-pp", line 9, in <module>
    load_entry_point('MarkdownPP==1.5.1', 'console_scripts', 'markdown-pp')()
  File "/usr/lib/python2.7/site-packages/MarkdownPP/main.py", line 112, in main
    MarkdownPP.MarkdownPP(input=mdpp, output=md, modules=modules)
  File "/usr/lib/python2.7/site-packages/MarkdownPP/MarkdownPP.py", line 28, in __init__
    pp.process()
  File "/usr/lib/python2.7/site-packages/MarkdownPP/Processor.py", line 49, in process
    transforms = module.transform(self.data)
  File "/usr/lib/python2.7/site-packages/MarkdownPP/Modules/Include.py", line 40, in transform
    includedata = self.include(match)
  File "/usr/lib/python2.7/site-packages/MarkdownPP/Modules/Include.py", line 106, in include
    result += self.include_file(filename, pwd, shift)
  File "/usr/lib/python2.7/site-packages/MarkdownPP/Modules/Include.py", line 74, in include_file
    data[linenum] = "#" + data[linenum]
**UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 2: ordinal not in range(128)**

[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'index' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
**pandoc: /root/FuqiangWorks/templates/pandoc/ivy.css: openBinaryFile: does not exist (No such file or directory)**

**Comment by fujohnwang** [comment]
先安装markdown-pp，亲

然后好像ivy.css在我本地另一个目录下，我修正一下哈

**Comment by fujohnwang** [comment]
OK了， 你可以update然后再试一下 ；）
